-- ========================================
-- 数据管理模块数据库设计
-- 数据库: MySQL 8.0
-- 字符集: utf8mb4
-- ========================================

USE lims;

-- ========================================
-- 9. 数据管理模块表
-- ========================================

-- 动态表单字段配置表
CREATE TABLE det_form_field (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    method_id BIGINT NOT NULL COMMENT '标准方法ID',
    method_code VARCHAR(50) COMMENT '标准方法编号',
    field_code VARCHAR(50) NOT NULL COMMENT '字段编码',
    field_name VARCHAR(100) NOT NULL COMMENT '字段名称',
    field_type VARCHAR(20) NOT NULL COMMENT '字段类型 input number select date textarea file',
    data_type VARCHAR(20) DEFAULT 'string' COMMENT '数据类型 string number boolean date',
    unit VARCHAR(20) COMMENT '计量单位',
    detection_limit DECIMAL(12,4) COMMENT '检出限',
    quantitation_limit DECIMAL(12,4) COMMENT '定量限',
    min_value DECIMAL(12,4) COMMENT '最小值',
    max_value DECIMAL(12,4) COMMENT '最大值',
    precision_scale INT DEFAULT 2 COMMENT '精度（小数位数）',
    required TINYINT DEFAULT 1 COMMENT '是否必填 0否 1是',
    sort_order INT DEFAULT 0 COMMENT '排序',
    options TEXT COMMENT '选项值(JSON格式，用于下拉选择)',
    placeholder VARCHAR(200) COMMENT '输入提示',
    description VARCHAR(500) COMMENT '字段说明',
    status TINYINT DEFAULT 1 COMMENT '状态 0停用 1启用',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by BIGINT COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_method_field (method_id, field_code),
    KEY idx_method_id (method_id),
    KEY idx_field_code (field_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='动态表单字段配置表';

-- 检测数据表（主表）
CREATE TABLE det_data_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    record_no VARCHAR(30) NOT NULL COMMENT '记录编号',
    task_id BIGINT NOT NULL COMMENT '检测任务ID',
    task_no VARCHAR(30) COMMENT '任务编号',
    sample_id BIGINT COMMENT '样品ID',
    sample_no VARCHAR(50) COMMENT '样品编号',
    sample_name VARCHAR(100) COMMENT '样品名称',
    entrust_id BIGINT COMMENT '委托单ID',
    entrust_no VARCHAR(30) COMMENT '委托单编号',
    method_id BIGINT COMMENT '标准方法ID',
    method_code VARCHAR(50) COMMENT '标准方法编号',
    method_name VARCHAR(200) COMMENT '标准方法名称',
    equipment_ids TEXT COMMENT '使用设备ID列表(JSON格式)',
    equipment_names TEXT COMMENT '使用设备名称列表(JSON格式)',
    standard_substance_ids TEXT COMMENT '标准物质ID列表(JSON格式)',
    standard_substance_names TEXT COMMENT '标准物质名称列表(JSON格式)',
    test_date DATE COMMENT '检测日期',
    test_time TIME COMMENT '检测时间',
    test_env TEXT COMMENT '检测环境条件(JSON格式: 温度、湿度、气压等)',
    data_source TINYINT DEFAULT 1 COMMENT '数据来源 1手动录入 2仪器导入 3文件导入',
    import_file_url VARCHAR(255) COMMENT '导入文件地址',
    import_file_name VARCHAR(255) COMMENT '导入文件名称',
    entry_user_id BIGINT COMMENT '录入人ID',
    entry_user_name VARCHAR(50) COMMENT '录入人姓名',
    entry_time DATETIME COMMENT '录入时间',
    data_hash VARCHAR(64) COMMENT '数据哈希值（防篡改）',
    first_review_user_id BIGINT COMMENT '一级审核人ID',
    first_review_user_name VARCHAR(50) COMMENT '一级审核人姓名',
    first_review_time DATETIME COMMENT '一级审核时间',
    first_review_opinion VARCHAR(1000) COMMENT '一级审核意见',
    first_review_result TINYINT COMMENT '一级审核结果 1通过 2驳回',
    second_review_user_id BIGINT COMMENT '二级审核人ID',
    second_review_user_name VARCHAR(50) COMMENT '二级审核人姓名',
    second_review_time DATETIME COMMENT '二级审核时间',
    second_review_opinion VARCHAR(1000) COMMENT '二级审核意见',
    second_review_result TINYINT COMMENT '二级审核结果 1通过 2驳回',
    review_status TINYINT DEFAULT 0 COMMENT '审核状态 0待审核 1一级审核中 2一级审核通过 3一级审核驳回 4二级审核中 5二级审核通过 6二级审核驳回',
    has_oos TINYINT DEFAULT 0 COMMENT '是否有OOS 0否 1是',
    oos_count INT DEFAULT 0 COMMENT 'OOS数量',
    status TINYINT DEFAULT 0 COMMENT '状态 0草稿 1已录入 2审核中 3已完成 4已退回',
    version INT DEFAULT 1 COMMENT '版本号（乐观锁）',
    remark VARCHAR(1000) COMMENT '备注',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by BIGINT COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_record_no (record_no),
    KEY idx_task_id (task_id),
    KEY idx_sample_id (sample_id),
    KEY idx_entrust_id (entrust_id),
    KEY idx_method_id (method_id),
    KEY idx_review_status (review_status),
    KEY idx_status (status),
    KEY idx_entry_user_id (entry_user_id),
    KEY idx_has_oos (has_oos)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测数据表';

-- 检测数据明细表
CREATE TABLE det_data_record_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    record_id BIGINT NOT NULL COMMENT '检测数据记录ID',
    record_no VARCHAR(30) COMMENT '记录编号',
    field_id BIGINT COMMENT '表单字段ID',
    field_code VARCHAR(50) NOT NULL COMMENT '字段编码',
    field_name VARCHAR(100) NOT NULL COMMENT '字段名称',
    item_id BIGINT COMMENT '检测项目ID',
    item_code VARCHAR(30) COMMENT '检测项目编码',
    item_name VARCHAR(100) COMMENT '检测项目名称',
    unit VARCHAR(20) COMMENT '计量单位',
    detection_limit DECIMAL(12,4) COMMENT '检出限',
    quantitation_limit DECIMAL(12,4) COMMENT '定量限',
    limit_value VARCHAR(100) COMMENT '限值要求',
    min_value DECIMAL(12,4) COMMENT '最小值',
    max_value DECIMAL(12,4) COMMENT '最大值',
    result_value VARCHAR(500) COMMENT '结果值',
    result_numeric DECIMAL(16,4) COMMENT '数值结果',
    is_nd TINYINT DEFAULT 0 COMMENT '是否未检出 0否 1是',
    is_oos TINYINT DEFAULT 0 COMMENT '是否超标 0否 1是',
    oos_type VARCHAR(50) COMMENT '超标类型 OOS/OOT',
    original_result VARCHAR(500) COMMENT '原始结果（仪器读数）',
    remark VARCHAR(500) COMMENT '备注',
    sort_order INT DEFAULT 0 COMMENT '排序',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by BIGINT COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_record_id (record_id),
    KEY idx_field_id (field_id),
    KEY idx_item_id (item_id),
    KEY idx_is_oos (is_oos)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测数据明细表';

-- 电子原始记录表
CREATE TABLE det_original_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    record_no VARCHAR(30) NOT NULL COMMENT '原始记录编号',
    data_record_id BIGINT NOT NULL COMMENT '检测数据记录ID',
    data_record_no VARCHAR(30) COMMENT '检测数据记录编号',
    task_id BIGINT COMMENT '检测任务ID',
    task_no VARCHAR(30) COMMENT '任务编号',
    sample_id BIGINT COMMENT '样品ID',
    sample_no VARCHAR(50) COMMENT '样品编号',
    template_id BIGINT COMMENT '模板ID',
    template_name VARCHAR(100) COMMENT '模板名称',
    record_type VARCHAR(50) COMMENT '记录类型 水质检测 空气检测 土壤检测',
    title VARCHAR(200) COMMENT '记录标题',
    content TEXT COMMENT '记录内容(JSON格式，富文本)',
    html_content TEXT COMMENT 'HTML格式内容（用于预览）',
    signature_info TEXT COMMENT '签名信息(JSON格式)',
    attachment_urls TEXT COMMENT '附件地址列表(JSON格式)',
    attachment_names TEXT COMMENT '附件名称列表(JSON格式)',
    permission_type TINYINT DEFAULT 1 COMMENT '权限类型 1只读 2可写',
    permission_users TEXT COMMENT '授权用户ID列表(JSON格式)',
    permission_roles TEXT COMMENT '授权角色编码列表(JSON格式)',
    data_hash VARCHAR(64) COMMENT '内容哈希值（防篡改）',
    edit_count INT DEFAULT 0 COMMENT '编辑次数',
    last_edit_user_id BIGINT COMMENT '最后编辑人ID',
    last_edit_user_name VARCHAR(50) COMMENT '最后编辑人姓名',
    last_edit_time DATETIME COMMENT '最后编辑时间',
    status TINYINT DEFAULT 0 COMMENT '状态 0草稿 1编辑中 2已提交 3已归档',
    version INT DEFAULT 1 COMMENT '版本号',
    remark VARCHAR(1000) COMMENT '备注',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by BIGINT COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_record_no (record_no),
    KEY idx_data_record_id (data_record_id),
    KEY idx_task_id (task_id),
    KEY idx_sample_id (sample_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子原始记录表';

-- 原始记录版本历史表
CREATE TABLE det_original_record_version (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    original_record_id BIGINT NOT NULL COMMENT '原始记录ID',
    original_record_no VARCHAR(30) COMMENT '原始记录编号',
    version INT NOT NULL COMMENT '版本号',
    content TEXT COMMENT '记录内容(JSON格式)',
    html_content TEXT COMMENT 'HTML格式内容',
    data_hash VARCHAR(64) COMMENT '内容哈希值',
    change_type VARCHAR(30) COMMENT '变更类型 创建 修改 提交 归档',
    change_reason VARCHAR(500) COMMENT '变更原因',
    operator_id BIGINT COMMENT '操作人ID',
    operator_name VARCHAR(50) COMMENT '操作人姓名',
    operate_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    PRIMARY KEY (id),
    KEY idx_original_record_id (original_record_id),
    KEY idx_version (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原始记录版本历史表';

-- 数据审核记录表
CREATE TABLE det_data_review (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    data_record_id BIGINT NOT NULL COMMENT '检测数据记录ID',
    data_record_no VARCHAR(30) COMMENT '检测数据记录编号',
    review_level TINYINT NOT NULL COMMENT '审核级别 1一级审核(自审) 2二级审核(科室负责人)',
    reviewer_id BIGINT NOT NULL COMMENT '审核人ID',
    reviewer_name VARCHAR(50) COMMENT '审核人姓名',
    review_opinion VARCHAR(2000) COMMENT '审核意见',
    review_result TINYINT NOT NULL COMMENT '审核结果 1通过 2驳回',
    review_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '审核时间',
    reject_reason VARCHAR(1000) COMMENT '驳回原因',
    corrected_data TEXT COMMENT '修正后数据(JSON格式)',
    is_modified TINYINT DEFAULT 0 COMMENT '是否修改数据 0否 1是',
    remark VARCHAR(500) COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_data_record_id (data_record_id),
    KEY idx_review_level (review_level),
    KEY idx_review_result (review_result)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据审核记录表';

-- OOS超标预警记录表
CREATE TABLE det_oos_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    oos_no VARCHAR(30) NOT NULL COMMENT 'OOS编号',
    data_record_id BIGINT NOT NULL COMMENT '检测数据记录ID',
    data_record_no VARCHAR(30) COMMENT '检测数据记录编号',
    data_item_id BIGINT COMMENT '检测数据明细ID',
    task_id BIGINT COMMENT '检测任务ID',
    task_no VARCHAR(30) COMMENT '任务编号',
    sample_id BIGINT COMMENT '样品ID',
    sample_no VARCHAR(50) COMMENT '样品编号',
    item_id BIGINT COMMENT '检测项目ID',
    item_code VARCHAR(30) COMMENT '检测项目编码',
    item_name VARCHAR(100) COMMENT '检测项目名称',
    unit VARCHAR(20) COMMENT '计量单位',
    result_value DECIMAL(16,4) NOT NULL COMMENT '检测结果',
    limit_value VARCHAR(100) COMMENT '限值要求',
    limit_min DECIMAL(16,4) COMMENT '最小限值',
    limit_max DECIMAL(16,4) COMMENT '最大限值',
    deviation_rate DECIMAL(10,2) COMMENT '偏差率(%)',
    oos_type VARCHAR(20) DEFAULT 'OOS' COMMENT '超标类型 OOS OOT',
    oos_level TINYINT DEFAULT 1 COMMENT '超标等级 1一般 2严重 3重大',
    discovery_time DATETIME COMMENT '发现时间',
    discovery_user_id BIGINT COMMENT '发现人ID',
    discovery_user_name VARCHAR(50) COMMENT '发现人姓名',
    investigation_result TEXT COMMENT '调查结果',
    cause_analysis TEXT COMMENT '原因分析',
    handling_measure TEXT COMMENT '处理措施',
    corrective_action TEXT COMMENT '纠正措施',
    preventive_action TEXT COMMENT '预防措施',
    investigator_user_id BIGINT COMMENT '调查人ID',
    investigator_user_name VARCHAR(50) COMMENT '调查人姓名',
    investigation_start_time DATETIME COMMENT '调查开始时间',
    investigation_end_time DATETIME COMMENT '调查结束时间',
    review_user_id BIGINT COMMENT '审核人ID',
    review_user_name VARCHAR(50) COMMENT '审核人姓名',
    review_opinion VARCHAR(1000) COMMENT '审核意见',
    review_result TINYINT COMMENT '审核结果 1通过 2驳回',
    review_time DATETIME COMMENT '审核时间',
    close_user_id BIGINT COMMENT '关闭人ID',
    close_user_name VARCHAR(50) COMMENT '关闭人姓名',
    close_time DATETIME COMMENT '关闭时间',
    close_opinion VARCHAR(1000) COMMENT '关闭意见',
    status TINYINT DEFAULT 0 COMMENT '状态 0待调查 1调查中 2待审核 3已完成 4已关闭',
    is_closed TINYINT DEFAULT 0 COMMENT '是否闭环 0否 1是',
    remark VARCHAR(1000) COMMENT '备注',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记',
    create_by BIGINT COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by BIGINT COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_oos_no (oos_no),
    KEY idx_data_record_id (data_record_id),
    KEY idx_task_id (task_id),
    KEY idx_sample_id (sample_id),
    KEY idx_item_id (item_id),
    KEY idx_oos_type (oos_type),
    KEY idx_status (status),
    KEY idx_is_closed (is_closed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OOS超标预警记录表';

-- OOS处理流程记录表
CREATE TABLE det_oos_process_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    oos_id BIGINT NOT NULL COMMENT 'OOS记录ID',
    oos_no VARCHAR(30) COMMENT 'OOS编号',
    process_node VARCHAR(50) NOT NULL COMMENT '流程节点 发现 分配 调查 审核 关闭',
    process_content TEXT COMMENT '处理内容',
    operator_id BIGINT COMMENT '操作人ID',
    operator_name VARCHAR(50) COMMENT '操作人姓名',
    operate_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    attachment_urls TEXT COMMENT '附件地址列表(JSON格式)',
    remark VARCHAR(500) COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_oos_id (oos_id),
    KEY idx_process_node (process_node)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OOS处理流程记录表';

-- 数据溯源关系表
CREATE TABLE det_data_trace (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    trace_type VARCHAR(30) NOT NULL COMMENT '溯源类型 sample task equipment standard_substance',
    source_id BIGINT NOT NULL COMMENT '源节点ID',
    source_type VARCHAR(30) NOT NULL COMMENT '源节点类型',
    source_name VARCHAR(200) COMMENT '源节点名称',
    source_no VARCHAR(50) COMMENT '源节点编号',
    target_id BIGINT NOT NULL COMMENT '目标节点ID',
    target_type VARCHAR(30) NOT NULL COMMENT '目标节点类型',
    target_name VARCHAR(200) COMMENT '目标节点名称',
    target_no VARCHAR(50) COMMENT '目标节点编号',
    relation_type VARCHAR(30) COMMENT '关系类型 belong_to use_for generate',
    relation_desc VARCHAR(200) COMMENT '关系描述',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_source (source_type, source_id),
    KEY idx_target (target_type, target_id),
    KEY idx_trace_type (trace_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据溯源关系表';

-- 数据变更操作日志表（防篡改审计）
CREATE TABLE det_data_audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    data_type VARCHAR(30) NOT NULL COMMENT '数据类型 data_record original_record oos_record',
    data_id BIGINT NOT NULL COMMENT '数据ID',
    data_no VARCHAR(30) COMMENT '数据编号',
    operate_type VARCHAR(30) NOT NULL COMMENT '操作类型 create update delete submit review',
    field_name VARCHAR(100) COMMENT '修改字段名',
    old_value TEXT COMMENT '原值',
    new_value TEXT COMMENT '新值',
    operator_id BIGINT COMMENT '操作人ID',
    operator_name VARCHAR(50) COMMENT '操作人姓名',
    operate_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    ip_address VARCHAR(50) COMMENT 'IP地址',
    user_agent VARCHAR(500) COMMENT '用户代理',
    tamper_attempt TINYINT DEFAULT 0 COMMENT '是否篡改尝试 0否 1是',
    block_reason VARCHAR(500) COMMENT '拦截原因',
    remark VARCHAR(500) COMMENT '备注',
    PRIMARY KEY (id),
    KEY idx_data (data_type, data_id),
    KEY idx_operate_type (operate_type),
    KEY idx_operator_id (operator_id),
    KEY idx_tamper_attempt (tamper_attempt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据变更操作日志表';

-- ========================================
-- 初始化数据
-- ========================================

-- 初始化动态表单字段（基于标准方法）
INSERT INTO det_form_field (method_id, method_code, field_code, field_name, field_type, data_type, unit, detection_limit, precision_scale, required, sort_order, description) VALUES
(1, 'SM-W001', 'ph_value', 'pH值', 'number', 'number', '无量纲', 0.01, 2, 1, 1, '样品pH值测定结果'),
(1, 'SM-W001', 'temperature', '测定温度', 'number', 'number', '℃', NULL, 1, 1, 2, '测定时的温度'),
(1, 'SM-W001', 'instrument_type', '仪器型号', 'input', 'string', NULL, NULL, 0, 1, 3, '使用的pH计型号'),
(1, 'SM-W001', 'calibration_time', '校准时间', 'date', 'date', NULL, NULL, 0, 1, 4, '仪器校准时间'),
(1, 'SM-W001', 'parallel_sample_1', '平行样1', 'number', 'number', '无量纲', 0.01, 2, 1, 5, '平行样测定结果1'),
(1, 'SM-W001', 'parallel_sample_2', '平行样2', 'number', 'number', '无量纲', 0.01, 2, 1, 6, '平行样测定结果2'),
(1, 'SM-W001', 'relative_deviation', '相对偏差', 'number', 'number', '%', NULL, 2, 0, 7, '平行样相对偏差'),
(2, 'SM-W002', 'cod_value', 'COD值', 'number', 'number', 'mg/L', 5.0, 2, 1, 1, '化学需氧量测定结果'),
(2, 'SM-W002', 'digestion_time', '消解时间', 'number', 'number', 'min', NULL, 0, 1, 2, '消解时间'),
(2, 'SM-W002', 'digestion_temperature', '消解温度', 'number', 'number', '℃', NULL, 0, 1, 3, '消解温度'),
(2, 'SM-W002', 'blank_value', '空白值', 'number', 'number', 'mg/L', NULL, 2, 1, 4, '空白试验值'),
(2, 'SM-W002', 'parallel_1', '平行样1', 'number', 'number', 'mg/L', 5.0, 2, 1, 5, '平行样测定结果1'),
(2, 'SM-W002', 'parallel_2', '平行样2', 'number', 'number', 'mg/L', 5.0, 2, 1, 6, '平行样测定结果2'),
(2, 'SM-W002', 'relative_deviation', '相对偏差', 'number', 'number', '%', NULL, 2, 0, 7, '平行样相对偏差'),
(2, 'SM-W002', 'qc_recovery', '加标回收率', 'number', 'number', '%', NULL, 2, 0, 8, '加标回收率'),
(3, 'SM-W003', 'bod5_value', 'BOD5值', 'number', 'number', 'mg/L', 2.0, 2, 1, 1, '五日生化需氧量测定结果'),
(3, 'SM-W003', 'do_initial', '初始溶解氧', 'number', 'number', 'mg/L', NULL, 2, 1, 2, '培养前溶解氧'),
(3, 'SM-W003', 'do_final', '最终溶解氧', 'number', 'number', 'mg/L', NULL, 2, 1, 3, '培养5天后溶解氧'),
(3, 'SM-W003', 'incubation_temp', '培养温度', 'number', 'number', '℃', NULL, 1, 1, 4, '恒温培养箱温度'),
(3, 'SM-W003', 'incubation_days', '培养天数', 'number', 'number', 'd', NULL, 0, 1, 5, '实际培养天数'),
(3, 'SM-W003', 'dilution_factor', '稀释倍数', 'number', 'number', '倍', NULL, 0, 1, 6, '样品稀释倍数'),
(4, 'SM-A001', 'pm25_value', 'PM2.5浓度', 'number', 'number', 'μg/m³', 0.001, 3, 1, 1, 'PM2.5质量浓度'),
(4, 'SM-A001', 'pm10_value', 'PM10浓度', 'number', 'number', 'μg/m³', 0.001, 3, 1, 2, 'PM10质量浓度'),
(4, 'SM-A001', 'sampling_flow', '采样流量', 'number', 'number', 'L/min', NULL, 2, 1, 3, '采样器流量'),
(4, 'SM-A001', 'sampling_time', '采样时间', 'number', 'number', 'min', NULL, 0, 1, 4, '实际采样时间'),
(4, 'SM-A001', 'sampling_volume', '采样体积', 'number', 'number', 'm³', NULL, 4, 1, 5, '标准状态下采样体积'),
(4, 'SM-A001', 'filter_weight_before', '滤膜前重', 'number', 'number', 'mg', NULL, 4, 1, 6, '采样前滤膜重量'),
(4, 'SM-A001', 'filter_weight_after', '滤膜后重', 'number', 'number', 'mg', NULL, 4, 1, 7, '采样后滤膜重量'),
(4, 'SM-A001', 'weight_diff', '重量差', 'number', 'number', 'mg', NULL, 4, 1, 8, '滤膜增重'),
(5, 'SM-S001', 'cd_value', '镉(Cd)含量', 'number', 'number', 'mg/kg', 0.01, 4, 1, 1, '土壤中镉的含量'),
(5, 'SM-S001', 'pb_value', '铅(Pb)含量', 'number', 'number', 'mg/kg', 0.1, 4, 1, 2, '土壤中铅的含量'),
(5, 'SM-S001', 'cr_value', '铬(Cr)含量', 'number', 'number', 'mg/kg', 0.5, 4, 1, 3, '土壤中铬的含量'),
(5, 'SM-S001', 'digestion_method', '消解方法', 'select', 'string', NULL, NULL, 0, 1, 4, '样品前处理方法'),
(5, 'SM-S001', 'instrument_model', '仪器型号', 'input', 'string', NULL, NULL, 0, 1, 5, 'ICP-OES仪器型号'),
(5, 'SM-S001', 'rf_power', '射频功率', 'number', 'number', 'W', NULL, 0, 1, 6, '仪器射频功率'),
(5, 'SM-S001', 'plasma_flow', '等离子体流量', 'number', 'number', 'L/min', NULL, 2, 1, 7, '等离子体氩气流量'),
(5, 'SM-S001', 'auxiliary_flow', '辅助气流量', 'number', 'number', 'L/min', NULL, 2, 1, 8, '辅助气流量'),
(5, 'SM-S001', 'nebulizer_flow', '雾化器流量', 'number', 'number', 'L/min', NULL, 2, 1, 9, '雾化器流量');

-- 初始化动态表单字段选项
UPDATE det_form_field SET options = '["电热板消解","微波消解","湿法消解"]' WHERE field_code = 'digestion_method';
